<html>
<table width="100%" cellspacing="2" cellpadding="2" border="1">
<tbody>
<tr>
<td valign="center" align="center" width="25%"><img src="../../media/decartes.jpg"
alt="DeCART Icon" width="128" height="171"><br>
</td>
<td valign="center" align="center" width="75%">
<h1 align="center"><font size="+3">DeCART Summer School<br>
for<br>
Biomedical Data Science</font></h1></td>
<td valign="center" align="center" width="25%"><img
src="../../media/U_Health_stacked_png_red.png" alt="Utah Health
Logo" width="128" height="134"><br>
</td>
</tr>
</tbody>
</table>
<br>
</html>


#  Numerics

There are multiple types of numbers, each arising from different uses that generated them.

>Numbers arose from the formalization of two different human-cognitive conceptions: counting and measurement. Based on fossil records, anthropologists believe that both concepts existed and were used many thousands of years before numbers were introduced. As early as 35,000 years ago, humans put notches into bones (and probably wooden sticks as well, but none have survived and been found) to record things---possibly the cycles of the moon or the seasons---and it seems probable they used sticks or lengths of vine to measure lengths. Numbers themselves, however---abstractions that stand for the number of notches on a bone or the length of a measuring device---appear to have first appeared much later, around 10,000 years ago in the case of counting collections. 
>
>These activities resulted in two different kinds of number: the discrete counting numbers and the continuous real numbers. The connection between these two kinds of numbers was not finally put onto a firm footing until the nineteenth century, with the construction of the modern real number system. (Keith Devlin *Introduction to Mathematical Thinking*, p. 75) 

There are more than two types of numbers (see [Peter Alfeld's page](http://www.math.utah.edu/~pa/math/numbers.html)) and Python has two distinct types of numbers (five really, but we're going to ignore types 3, 4, and 5). Before we get into Python, let's review differnt types of numbers and talk about how we can represent them in a computer.

### To Simplify

#### Counting Numbers (Integers)
#### Measuring Numbers (Reals)

#  Numerics
## Two Python Numeric Types
* Integers: **roughly corresponding** to the Integers ($\mathbb{Z}$) of mathematics.
* Floating Point Numbers: **roughly corresponding** to the Reals ($\mathbb{R}$) of mathematics.


### Why "roughly corresponding"?
There are an infinitely many integers and real numbers. A computer consisting of a finite number of transitors cannot represent an infinite number of numbers, so there are design decisions that determine how large or small a number can be represented.


### Python Integers

Python integers are exact representations of a finite subset of the integers. The maximum (and minimum) integers that can be represented is hardware dependent. But the value for the computer your code is running on is available in the ``sys`` library.

For the computers used in this course, the value is $$2^{63}-1$$, because we are using a 64-bit system.

#### Why the -1? Why 63 not 64?

In [1]:
import sys 
print(sys.maxsize, 2**63 - 1)

9223372036854775807 9223372036854775807


### What happens if we exceed this value?

In [3]:
print(sys.maxsize+6)

9223372036854775813


### Is this what you expected?

#### Compare this behavior to Numpy arrays below.
#### What do we really mean by a maximum integer?

### Floating Point Numbers

Representing approximations of real numbers via floating point types is more complex, but the issue is the same: we only have so many bits to allocate to represent the number. Consequently floating point numbers are inherently **approximations.**

``sys.float_info`` contains information about the limits of floating point numbers.

*  See [Floating Point Arithmetic: Issues and Limitations](http://docs.python.org/3/tutorial/floatingpoint.html)
*  Also [The Perils of Floating Point](http://www.lahey.com/float.htm)
* Floating point numbers are coded by typing them as decimals

In [4]:
import sys
print("maximum float",sys.float_info.max)
print("minimum float",sys.float_info.min)
print("epislon",sys.float_info.epsilon)

maximum float 1.7976931348623157e+308
minimum float 2.2250738585072014e-308
epislon 2.220446049250313e-16


#### Because floating point numbers are approximations, you need to be careful with your concepts of equality

* Although is your data likely to differ by less than $2.2\times 10^{-16}$?

### Floating point numbers can also be typed in *exponential form.*

In [5]:
print(4e1)
print(4E1)


40.0
40.0


## Generating Floats

* Typing a number with a decimal
* Dividing two integers.
* Using the [``float``](https://docs.python.org/3/library/functions.html#float) function 


In [ ]:
print(9/3)
print(float(5))
print(float('5'))


# Biomedical Data and Python Data Types
### What would be the appropriate data type (Integer, Float, String) for the following quantities?

* Patient pulse as recorded at a clinic visit
* Patient blood pressure 
* My medical record number 
* Signal measured in an MRI scanner 
* Average breaths per minute over an hour
* The length of a tibia 
* My weight in kilograms 
* Days since last menustral period 
* DNA sequence 

## What can we do with numbers?

### Create expressions with basic arithmetic operators

* **"+"** addition
* **"-"** subtraction
* **"*"** multiplication
* **"/"** division (also "//")
* **"%"** modulus
* **"\*\*"** exponentiation

### Compare numbers
* **"=="** equal to **(this will be a frequent mistake)**
* **"!="** not equal to
* **"<"** less than
* **"<="** less than or equal to
* **">"** greater than
* **">=** greater than or equal to

In [6]:
print (5+3,type(5+3))
print (5-3,type(5-3))
print (5*3,type(5*3))
print (5/3,type(5/3)) 
print (5%3 ,type(5%3))
print (5**30 ,type(5**30))
print(4.3%2,type(4.3%2))
print(4.5*3)

print (5== 4)
print(5>4)
print("5>4",5>4)

8 <class 'int'>
2 <class 'int'>
15 <class 'int'>
1.6666666666666667 <class 'float'>
2 <class 'int'>
931322574615478515625 <class 'int'>
0.2999999999999998 <class 'float'>
13.5
False
True
5>4 True


In [ ]:
print(5=4)

### Python Operators Have Orders of Precedence

If you recall from mathematics, mathematical operators have order of precedence, that is which operator must be applied first. For example, in the equation "$5\times4-3$" would this be calculated as $20-3$ or $5\times1$?

Python's order of precedence is described [here](https://docs.python.org/3/reference/expressions.html). Expressions that have equal precedence are ordered from left to right.

In [7]:
print(5*3/2)
print(5/2*3)

7.5
7.5


#### What happens when you mix types?

In [ ]:
expr = "5+3"
print(eval(expr),type(eval(expr)))


#### What is the Rule?

 Python also provides a [``round``](https://docs.python.org/3/library/functions.html#round) function for floats.

#### Note Behavior of *round*. 

In [ ]:
print(round(5.7),type(round(5.7)))


### Comparison Operators for Numbers
* **"=="** equal to **(this will be a frequent mistake)**
* **"!="** not equal to
* **"<"** less than
* **"<="** less than or equal to
* **">"** greater than
* **">=** greater than or equal to

## Exercise

Use Python as a calculator to compute the following value:

\begin{equation}
\frac{(5\times 3^3-2)^2}{4\times 3+1}
\end{equation}

In [10]:
a = 5* 3 **3 -2
b= a**2
c= 4*3+1
d=b/c
print(d)
(5*3**3-2)**2/(4*3+1)

1360.6923076923076


In [11]:
numeric_quizz1(1360.6923076923076)

NameError: name 'numeric_quizz1' is not defined

## Exercise

\begin{equation}
7^{\frac{1}{2}}\times\frac{4}{3} < \frac{3^2\times\frac{3}{4}}{1+2^2}
\end{equation}

In [22]:
print(7**(1/2)*4/3)
print((3**2*3/4)/(1+2**2))

3.5276684147527875
1.35


In [16]:
%%bash
cp /home/jovyan/work/decart_bootcamp_part2/modules/module1/quizzes/numeric_quizzes.py \
/home/jovyan/work/decart_bootcamp_part2/modules/module2/quizzes/numeric_quizzes.py 


In [19]:
from quizzes.numeric_quizzes import *
numeric_quizz2(False)

'You got the correct answer'

In [ ]:
def numeric_quizz2(answer):
    if not isinstance(answer,bool):
        return "Your answer needs to be the Python value True or False. You provided the type %s"%type(answer)
    try:
        assert_equal(answer, 7**(0.5)*(4/3) < (3**2*(3/4))/(1+2**2))
        return "You got the correct answer"
    except Exception as error:
        return "You did not get the correct answer. Pay attention to parentheses and operator precedence: %s"%error


## Exercise

Use the ``math`` library to compute the following value

\begin{equation}
e^{-5^2\times cos(\frac{3\pi}{7})}
\end{equation}

In [23]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'trunc']

In [32]:
import math
a = math.e**(-5**2*math.cos(3*math.pi/7))
print (a)

0.0038371577761156625


In [29]:
from quizzes.numeric_quizzes import *
numeric_quizz3(0.0038371577761156625)

'You got the correct answer'

## [Numpy](http://www.numpy.org/)

Numpy arrays are collections of numbers that can be manipulated efficiently. The arrays have a *type* that specifies what the underlying representation of the number is. These types include the following integers:

* uint8 (unsigned integer represented with 8 bits)
* uint16 (unsigned integer represented with 16 bits)
* uint32 (unsigned integer represented with 32 bits)
* uint64 (unsigned integer represented with 64 bits)
* int8 (signed integer represented with 8 bits)
* int16 (signed integer represented with 16 bits)
* int32 (signed integer represented with 32 bits)
* int64 (signed integer represented with 64 bits)

### What is up with all these different types?
* Memory allocation
    * If you have a very big array, memory constraints might come into play
* Computational efficiency
    * What size matches the underlying hardware?
    
### How do we create numpy arrays?

```Python
import numpy as np # conventional alias for numpy

array1 = np.ones((3,3)) # create a 3x3 array of ones
array2 = np.zeros((4,2)) # create an array of zeros with 4 rows and 2 columns
array3 = np.array([[1,0],[0,1]], dtype=np.uint8)
```

* ``dtype`` stands for "data type". If we don't provide a value, Numpy will choose a "sensible" value based on the array values provided.

* Maximum integer size
    * What is the minimum and maximum integer that can be represented with a uint8 and a int8?
    

In [15]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=np.int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
   

In [2]:
import numpy as np
array3 = np.array([[1,0],[0,1]])
array1 = np.ones((3,3))
array2 = np.zeros((4,2))
print(array3)
print ("*"*5)
print(array2)
print ("*"*5)
print(array1)


[[1 0]
 [0 1]]
*****
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
*****
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [9]:
import numpy as np
np.array([-18,], dtype=np.uint8)

array([238], dtype=uint8)

### Operations on Numpy Arrays

* 

In [4]:
A= np.random.randint(-50, 50, size=(3,3), dtype=np.int8)
B= np.random.randint(-50, 50, size=(3,3), dtype=np.int16)
C= np.random.randint(-50, 50, size=(2,2))
print(A)
print("*"*42)
print(B)
print("*"*42)
print(C)

[[-24  43 -27]
 [ 43 -19  49]
 [-43 -40  39]]
******************************************
[[-36 -23  42]
 [-33 -15   9]
 [ 15 -31  15]]
******************************************
[[-10 -39]
 [ 27  23]]


In [11]:
print(A + B)

[[-77 -26 -19]
 [ 24 -20  43]
 [ -3 -27  48]]


In [16]:
print(A*B)

[[ 1426    48    60]
 [-1225  -429   390]
 [ -868   110    47]]


In [17]:
np.abs(A)

array([[46,  2, 15],
       [49, 33, 13],
       [31, 22, 47]], dtype=int8)

In [5]:
print(A*C)

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [6]:
np.exp(A)

/opt/conda/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([[  0.,  inf,   0.],
       [ inf,   0.,  inf],
       [  0.,   0.,  inf]], dtype=float16)

In [20]:
help(np.exp)

Help on ufunc object:

exp = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y, ou