<html>
<table width="100%" cellspacing="2" cellpadding="2" border="1">
<tbody>
<tr>
<td valign="center" align="center" width="25%"><img src="../../media/decartes.jpg"
alt="DeCART Icon" width="128" height="171"><br>
</td>
<td valign="center" align="center" width="75%">
<h1 align="center"><font size="+3">DeCART Summer School<br>
for<br>
Biomedical Data Science</font></h1></td>
<td valign="center" align="center" width="25%"><img
src="../../media/U_Health_stacked_png_red.png" alt="Utah Health
Logo" width="128" height="134"><br>
</td>
</tr>
</tbody>
</table>
<br>
</html>


#  Numerics

There are multiple types of numbers, each arising from different uses that generated them.

>Numbers arose from the formalization of two different human-cognitive conceptions: counting and measurement. Based on fossil records, anthropologists believe that both concepts existed and were used many thousands of years before numbers were introduced. As early as 35,000 years ago, humans put notches into bones (and probably wooden sticks as well, but none have survived and been found) to record things---possibly the cycles of the moon or the seasons---and it seems probable they used sticks or lengths of vine to measure lengths. Numbers themselves, however---abstractions that stand for the number of notches on a bone or the length of a measuring device---appear to have first appeared much later, around 10,000 years ago in the case of counting collections. 
>
>These activities resulted in two different kinds of number: the discrete counting numbers and the continuous real numbers. The connection between these two kinds of numbers was not finally put onto a firm footing until the nineteenth century, with the construction of the modern real number system. (Keith Devlin *Introduction to Mathematical Thinking*, p. 75) 

There are more than two types of numbers (see [Peter Alfeld's page](http://www.math.utah.edu/~pa/math/numbers.html)) and Python has two distinct types of numbers (five really, but we're going to ignore types 3, 4, and 5). Before we get into Python, let's review differnt types of numbers and talk about how we can represent them in a computer.

### To Simplify

#### Counting Numbers (Integers)
#### Measuring Numbers (Reals)

#  Numerics
## Two Python Numeric Types
* Integers: **roughly corresponding** to the Integers ($\mathbb{Z}$) of mathematics.
* Floating Point Numbers: **roughly corresponding** to the Reals ($\mathbb{R}$) of mathematics.


### Why "roughly corresponding"?
There are an infinitely many integers and real numbers. A computer consisting of a finite number of transitors cannot represent an infinite number of numbers, so there are design decisions that determine how large or small a number can be represented.


### Python Integers

In [1]:
import sys
print("maximum float",sys.float_info.max)
print("minimum float",sys.float_info.min)
print("epislon",sys.float_info.epsilon)

maximum float 1.7976931348623157e+308
minimum float 2.2250738585072014e-308
epislon 2.220446049250313e-16


In [3]:
help(sys.float_info.epsilon)

Help on float object:

class float(object)
 |  float(x) -> floating point number
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      float.__format__(format_spec) -> string
 |      
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getformat__(...) from builtins.type
 |      float.__getformat__(typestr) -> string
 |      
 |      You probably don't want to use thi

#### Converting to Integers

Python also provides the [``int()``](https://docs.python.org/3/library/functions.html#int) for converting numbers or strings to integers. 


In [4]:
print(int(4.8))
print(int('67'))

4
67


In [5]:
print(int('hello'))

ValueError: invalid literal for int() with base 10: 'hello'

### Floating Point Numbers

Representing approximations of real numbers via floating point types is more complex, but the issue is the same: we only have so many bits to allocate to represent the number. Consequently floating point numbers are inherently **approximations.**

``sys.float_info`` contains information about the limits of floating point numbers.

*  See [Floating Point Arithmetic: Issues and Limitations](http://docs.python.org/3/tutorial/floatingpoint.html)
*  Also [The Perils of Floating Point](http://www.lahey.com/float.htm)
* Floating point numbers are coded by typing them as decimals

In [6]:
print(type(4))
print(type(4.))
print(type(4.0))

<class 'int'>
<class 'float'>
<class 'float'>


Floating point numbers can also be typed in *exponential form.*

In [7]:
print(4e1)
print(4E1)


40.0
40.0


## Generating Floats

* Floats can also be generated by dividing two integers.

* Similar to the ``int()`` function, Python provides a [``float``](https://docs.python.org/3/library/functions.html#float) function that will take a number or a string and convert it to a float.


In [8]:
print(9/3)
print(float(5))
print(float('5'))
print(float('five'))

3.0
5.0
5.0


ValueError: could not convert string to float: 'five'

# Biomedical Data and Python Data Types
### What would be the appropriate data type (Integer, Float, String) for the following quantities?

* Patient pulse as recorded at a clinic visit
* Patient blood pressure 
* My medical record number 
* Signal measured in an MRI scanner 
* Average breaths per minute over an hour
* The length of a tibia 
* My weight in kilograms 
* Days since last menustral period 
* DNA sequence 

## What can we do with numbers?

### Create expressions with basic arithmetic operators

* **"+"** addition
* **"-"** subtraction
* **"*"** multiplication
* **"/"** division (also "//")
* **"%"** modulus
* **"\*\*"** exponentiation

### Compare numbers
* **"=="** equal to **(this will be a frequent mistake)**
* **"!="** not equal to
* **"<"** less than
* **"<="** less than or equal to
* **">"** greater than
* **">=** greater than or equal to

In [10]:
print (5+3,type(5+3))
print (5-3,type(5-3))
print (5*3,type(5*3))
print (5/3,type(5/3)) 
print (5%3 ,type(5%3))
print (5**30 ,type(5**30))
print(4.6%2,type(4.3%2))
print(4.5*3)

print (5== 4)
print(5>4)
print("5>4",5>4)

8 <class 'int'>
2 <class 'int'>
15 <class 'int'>
1.6666666666666667 <class 'float'>
2 <class 'int'>
931322574615478515625 <class 'int'>
0.5999999999999996 <class 'float'>
13.5
False
True
5>4 True


In [12]:
print(5==4)

False


### Python Operators Have Orders of Precedence

If you recall from mathematics, mathematical operators have order of precedence, that is which operator must be applied first. For example, in the equation "$5\times4-3$" would this be calculated as $20-3$ or $5\times1$?

Python's order of precedence is described [here](https://docs.python.org/3/reference/expressions.html). Expressions that have equal precedence are ordered from left to right.

In [13]:
print(5*3/2)
print(5/2*3)

7.5
7.5


#### What happens when you mix types?

In [15]:
help(eval)

Help on built-in function eval in module builtins:

eval(source, globals=None, locals=None, /)
    Evaluate the given source in the context of globals and locals.
    
    The source may be a string representing a Python expression
    or a code object as returned by compile().
    The globals must be a dictionary and locals can be any mapping,
    defaulting to the current globals and locals.
    If only globals is given, locals defaults to it.



In [14]:
expr = "5+3"
print(eval(expr),type(eval(expr)))


8 <class 'int'>


#### What is the Rule?

 Python also provides a [``round``](https://docs.python.org/3/library/functions.html#round) function for floats.

#### Note Behavior of *round*. 

In [17]:
print(round(5.2),type(round(5.7)))


5 <class 'int'>


### Comparison Operators for Numbers
* **"=="** equal to **(this will be a frequent mistake)**
* **"!="** not equal to
* **"<"** less than
* **"<="** less than or equal to
* **">"** greater than
* **">=** greater than or equal to

## Exercise

Use Python as a calculator to compute the following value:

\begin{equation}
\frac{(5\times 3^3-2)^2}{4\times 3+1}
\end{equation}

In [18]:
print((5*3**3-2)**2/(4*3+1))

1360.6923076923076


In [19]:
numeric_quizz1(1360.6923076923076)

NameError: name 'numeric_quizz1' is not defined

## Exercise

\begin{equation}
7^{\frac{1}{2}}\times\frac{4}{3} < \frac{3^2\times\frac{3}{4}}{1+2^2}
\end{equation}

In [ ]:
numeric_quizz2("replace_me_with_True_or_False")

In [ ]:
def numeric_quizz2(answer):
    if not isinstance(answer,bool):
        return "Your answer needs to be the Python value True or False. You provided the type %s"%type(answer)
    try:
        assert_equal(answer, 7**(0.5)*(4/3) < (3**2*(3/4))/(1+2**2))
        return "You got the correct answer"
    except Exception as error:
        return "You did not get the correct answer. Pay attention to parentheses and operator precedence: %s"%error


In [21]:
print(7**(1/2)*4/3 < (3**2*3/4)/(1+2**2))

False


# Some Important Numeric Libraries

## [math](http://docs.python.org/3/library/math.html)
* Additional mathematical functions and constants
* Functions and constants are accessed via the **dot notation**.

## Exercise

Use the ``math`` library to compute the following value

\begin{equation}
e^{-5^2\times cos(\frac{3\pi}{7})}
\end{equation}

In [22]:
import math
print(math.e**(-5**2*math.cos(3*math.pi/7)))

0.0038371577761156625


In [23]:
numeric_quizz3(0.0038371577761156625)

NameError: name 'numeric_quizz3' is not defined

In [29]:
x=6
print (x + 2)
print (type(True))

8
<class 'bool'>


In [ ]:
import numpy as np

## [Numpy](http://www.numpy.org/)

Numpy arrays are collections of numbers that can be manipulated efficiently. The arrays have a *type* that specifies what the underlying representation of the number is. These types include the following integers:

* uint8 (unsigned integer represented with 8 bits)
* uint16 (unsigned integer represented with 16 bits)
* uint32 (unsigned integer represented with 32 bits)
* uint64 (unsigned integer represented with 64 bits)
* int8 (signed integer represented with 8 bits)
* int16 (signed integer represented with 16 bits)
* int32 (signed integer represented with 32 bits)
* int64 (signed integer represented with 64 bits)

### What is up with all these different types?
* Memory allocation
    * If you have a very big array, memory constraints might come into play
* Computational efficiency
    * What size matches the underlying hardware?
    
### How do we create numpy arrays?

```Python
import numpy as np # conventional alias for numpy

array1 = np.ones((3,3)) # create a 3x3 array of ones
array2 = np.zeros((4,2)) # create an array of zeros with 4 rows and 2 columns
array3 = np.array([[1,0],[0,1]], dtype=np.uint8)
```

* ``dtype`` stands for "data type". If we don't provide a value, Numpy will choose a "sensible" value based on the array values provided.

* Maximum integer size
    * What is the minimum and maximum integer that can be represented with a uint8 and a int8?
    

In [36]:
import numpy as np
np.array([-126,], dtype=np.int8)

array([-126], dtype=int8)

In [47]:
import numpy as np
a = np.array([[1,2],[10,11], [3,4]])
print(a)
print (a.shape)
b = np.array([[1,2,3],[4,5,6]])
print (b)
print (type(b))


[[ 1  2]
 [10 11]
 [ 3  4]]
(3, 2)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [43]:
array3 = np.array([[1,0],[0,1]], dtype=np.uint8)
print (array3)
print ("*"*5)
array1 = np.ones((3,3))
print (array1)
print (type(array1))
array2 = np.zeros((4,2))
print (array2)


[[1 0]
 [0 1]]
*****
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<class 'numpy.ndarray'>
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [56]:
e = np.random.random((2,2)) 
print (e.shape)
print (e)

(2, 2)
[[ 0.60182453  0.84538813]
 [ 0.68601369  0.43477924]]


In [53]:
d = np.eye(3)
print (d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Boolean Operations on Numpy Arrays

In [ ]:
2**8

In [ ]:
b = np.zeros((4,2))

In [ ]:
b.shape